version: "3.5"

services:
  mysql:  
    image: mysql:5.7
    container_name: mysql
    environment:
        MYSQL_DATABASE: adidas
        MYSQL_USER: user
        MYSQL_PASSWORD: 1111
        MYSQL_ROOT_PASSWORD: 1111
    ports:
      - "3307:3306"
    volumes:
      - my-db:/var/lib/mysql
  zookeeper:
      image: wurstmeister/zookeeper
      container_name: zookeeper
      ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"  

volumes:
  my-db: